export enum Role {
  ROOT = "ROOT",
  ADMIN = "ADMIN",
  USER = "USER",
  GUEST = "GUEST",
  DEV = "DEV",
}

export enum queryKeys {
  ACCOUNT = "ACCOUNT",
  INFO_USER = "INFO_USER",
  GET_INFO_USER = "GET_INFO_USER",
  GET_ALL_USER = "GET_ALL_USER",
  GET_LIST_FRIEND = "GET_LIST_FRIEND",
  GET_LIST_RECOMMEND_FRIEND = "GET_LIST_RECOMMEND_FRIEND",
  GET_LIST_FRIEND_REQUESTS_SENDER = "GET_LIST_FRIEND_REQUESTS_SENDER",
  GET_LIST_FRIEND_REQUESTS_RECEIVER = "GET_LIST_FRIEND_REQUESTS_RECEIVER",

  GET_All_TAG = "GET_All_TAG",
  GET_All_CHILD_TAG = "GET_All_CHILD_TAG",
  GET_TAG_BY_ID = "GET_TAG_BY_ID",
  GET_CHILD_TAG_BY_ID = "GET_CHILD_TAG_BY_ID",
  GET_All_CHILD_TAG_BY_SLUG = "GET_All_CHILD_TAG_BY_SLUG",

  GET_ALL_POST_RECENT = "GET_ALL_POST_RECENT",
  GET_LATEST_POSTS_PUBLIC = "GET_LATEST_POSTS_PUBLIC",
  GET_ALL_POST_BY_CATEGORY = "GET_ALL_POST_BY_CATEGORY",
  GET_POST_BY_ID = "GET_POST_BY_ID",
  GET_POST_BY_SLUG = "GET_POST_BY_SLUG",
  GET_ALL_POST_BY_VIEW = "GET_ALL_POST_BY_VIEW",
  GET_ALL_COMMENT_POST = "GET_ALL_COMMENT_BY_POST_ID",
  GET_ALL_REPLY_COMMENT_POST = "GET_ALL_REPLY_COMMENT_BY_POST_ID",

  GET_ALL_TAG_HEADER = "GET_ALL_TAG_HEADER",
  GET_DETAIL_TAG_BY_SLUG = "GET_DETAIL_TAG_BY_SLUG",

  GET_LIST_FILE = "GET_LIST_FILE",

  GET_FILE_STATISTIC = "GET_FILE_STATISTIC",

  GET_DATA_WEB = "GET_DATA_WEB",

  GET_ALL_ROLE = "GET_ALL_ROLE",

  GET_ALL_CHAT_GROUP = "GET_ALL_CHAT_GROUP",
  GET_ALL_CHAT_GROUP_COMMUNITY = "GET_ALL_CHAT_GROUP_COMMUNITY",
  GET_ALL_MESSAGES_GROUP = "GET_ALL_MESSAGES_GROUP",
  CHAT_GROUP_DETAIL = "CHAT_GROUP_DETAIL",
  GET_ALL_CHAT_GROUP_JOIN_REQUEST = "GET_ALL_CHAT_GROUP_JOIN_REQUEST",
}

export enum eventSocket {
  CONNECT = "connect",
  DISCONNECT = "disconnect",
  CONNECT_ERROR = "connect_error",
  RECONNECT = "reconnect",
  RECONNECT_ATTEMPT = "reconnect_attempt",
}

export enum tagNext {
  WEB = "WEB",
}

export enum statusPost {
  PUBLIC = "PUBLIC",
  SHARED = "SHARED",
  PRIVATE = "PRIVATE",
}

export const URL = process.env.NEXT_PUBLIC_CLIENT_URL || process.env.CLIENT_URL;
export const SECRET_KEY = process.env.SECRET_KEY;
export const KEY_MASTER = process.env.KEY_MASTER || "master";

export const LOGO_DEFAULT = `${URL}/image/minwandev.png`;
