export const buttonListOptions = [
  //["undo", "redo"],
  ["font", "fontSize", "formatBlock", "autoHeadingId"],
  ["outdent", "indent"],
  ["align", "horizontalRule", "list", "lineHeight"],
  ["bold", "underline", "italic", "strike", "subscript", "superscript"],
  ["fontColor", "hiliteColor", "textStyle"],
  ["removeFormat"],
  ["paragraphStyle", "blockquote"],
  [
    "table",
    "link",
    "image",
    //"video",
    // "audio",
    "math",
  ],
  //   [
  //     ":i-Tiện ích-default.more_vertical",
  //     // "preview",
  //     "fullScreen",
  //     "imageGallery",
  //     "showBlocks",
  //     "codeView",
  //     "print",
  //     "warningBlock",
  //     "customCodeHighlight",
  //   ],
  ["clearContent"],
  // ["save"],
  [
    "%1161",
    [
      // ["undo", "redo"],
      [
        ":p-Formats-default.more_paragraph",
        "font",
        "fontSize",
        "formatBlock",
        "paragraphStyle",
        "blockquote",
      ],
      ["bold", "underline", "italic", "strike", "subscript", "superscript"],
      ["fontColor", "hiliteColor", "textStyle"],
      ["removeFormat"],
      ["outdent", "indent"],
      ["align", "horizontalRule", "list", "lineHeight"],
      // ["-right", "save"],
      //   [
      //     "-right",
      //     ":i-Tiện ích-default.more_vertical",
      //     // "preview",
      //     "fullScreen",
      //     "imageGallery",
      //     "showBlocks",
      //     "codeView",
      //     "print",
      //   ],
      [
        "-right",
        ":r-Table&Media-default.more_plus",
        "table",
        "link",
        "image",
        // "video",
        //  "audio",
        "math",
      ],
      ["clearContent"],
    ],
  ],
  [
    "%893",
    [
      //["undo", "redo"],
      [
        ":p-Formats-default.more_paragraph",
        "font",
        "fontSize",
        "formatBlock",
        "paragraphStyle",
        "blockquote",
      ],
      ["bold", "underline", "italic", "strike"],
      [
        ":t-Fonts-default.more_text",
        "subscript",
        "superscript",
        "fontColor",
        "hiliteColor",
        "textStyle",
      ],
      ["removeFormat"],
      ["outdent", "indent"],
      ["align", "horizontalRule", "list", "lineHeight"],
      // ["-right", "save"],
      //   [
      //     "-right",
      //     ":i-Tiện ích-default.more_vertical",
      //     // "preview",
      //     "fullScreen",
      //     "imageGallery",
      //     "showBlocks",
      //     "codeView",
      //     "print",
      //   ],
      [
        "-right",
        ":r-Table&Media-default.more_plus",
        "table",
        "link",
        "image",
        //   "video",
        //  "audio",
        "math",
      ],
      ["clearContent"],
    ],
  ],
  [
    "%855",
    [
      //["undo", "redo"],
      [
        ":p-Formats-default.more_paragraph",
        "font",
        "fontSize",
        "formatBlock",
        "paragraphStyle",
        "blockquote",
      ],
      [
        ":t-Fonts-default.more_text",
        "bold",
        "underline",
        "italic",
        "strike",
        "subscript",
        "superscript",
        "fontColor",
        "hiliteColor",
        "textStyle",
      ],
      ["removeFormat"],
      ["outdent", "indent"],
      ["align", "horizontalRule", "list", "lineHeight"],
      [
        ":r-Table&Media-default.more_plus",
        "table",
        "link",
        "image",
        //  "video",
        // "audio",
        "math",
      ],
      // ["-right", "save"],
      //   [
      //     "-right",
      //     ":i-Tiện ích-default.more_vertical",
      //     // "preview",
      //     "fullScreen",
      //     "imageGallery",
      //     "showBlocks",
      //     "codeView",
      //     "print",
      //   ],
      ["clearContent"],
    ],
  ],
  [
    "%563",
    [
      // ["undo", "redo"],
      [
        ":p-Formats-default.more_paragraph",
        "font",
        "fontSize",
        "formatBlock",
        "paragraphStyle",
        "blockquote",
      ],
      [
        ":t-Fonts-default.more_text",
        "bold",
        "underline",
        "italic",
        "strike",
        "subscript",
        "superscript",
        "fontColor",
        "hiliteColor",
        "textStyle",
      ],
      ["removeFormat"],
      ["outdent", "indent"],
      [
        ":e-List&Line-default.more_horizontal",
        "align",
        "horizontalRule",
        "list",
        "lineHeight",
      ],
      [
        ":r-Table&Media-default.more_plus",
        "table",
        "link",
        "image",
        // "video",
        // "audio",
        "math",
      ],
      // ["-right", "save"],
      //   [
      //     "-right",
      //     ":i-Tiện ích-default.more_vertical",
      //     // "preview",
      //     "fullScreen",
      //     "imageGallery",
      //     "showBlocks",
      //     "codeView",
      //     "print",
      //   ],
      ["clearContent"],
    ],
  ],
  [
    "%458",
    [
      //  ["undo", "redo"],
      [
        ":p-Formats-default.more_paragraph",
        "font",
        "fontSize",
        "formatBlock",
        "paragraphStyle",
        "blockquote",
      ],
      [
        ":t-Fonts-default.more_text",
        "bold",
        "underline",
        "italic",
        "strike",
        "subscript",
        "superscript",
        "fontColor",
        "hiliteColor",
        "textStyle",
        "removeFormat",
      ],
      [
        ":e-List&Line-default.more_horizontal",
        "outdent",
        "indent",
        "align",
        "horizontalRule",
        "list",
        "lineHeight",
      ],
      [
        ":r-Table&Media-default.more_plus",
        "table",
        "link",
        "image",
        //"video",
        //"audio",
        "math",
      ],
      // ["-right", "save"],
      //   [
      //     "-right",
      //     ":i-Tiện ích-default.more_vertical",
      //     // "preview",
      //     "fullScreen",
      //     "imageGallery",
      //     "showBlocks",
      //     "codeView",
      //     "print",
      //   ],
      ["clearContent"],
    ],
  ],
];
