export const buttonListOptions = [
  ["undo", "redo"],
  ["font", "fontSize", "formatBlock", "autoHeadingId"],
  ["outdent", "indent"],
  ["align", "horizontalRule", "list", "lineHeight"],
  ["bold", "underline", "italic", "strike", "subscript", "superscript"],
  ["fontColor", "hiliteColor", "textStyle"],
  ["removeFormat"],
  ["paragraphStyle", "blockquote"],
  ["table", "link", "image", "video", "audio", "math"],
  [
    ":i-Tiện ích-default.more_vertical",
    // "preview",
    "fullScreen",
    "imageGallery",
    "showBlocks",
    "codeView",
    "print",
    "warningBlock",
    "customCodeHighlight",
  ],
  ["clearContent"],
  // ["save"],
  [
    "%1161",
    [
      ["undo", "redo"],
      [
        ":p-Formats-default.more_paragraph",
        "font",
        "fontSize",
        "formatBlock",
        "paragraphStyle",
        "blockquote",
      ],
      ["bold", "underline", "italic", "strike", "subscript", "superscript"],
      ["fontColor", "hiliteColor", "textStyle"],
      ["removeFormat"],
      ["outdent", "indent"],
      ["align", "horizontalRule", "list", "lineHeight"],
      // ["-right", "save"],
      [
        "-right",
        ":i-Tiện ích-default.more_vertical",
        // "preview",
        "fullScreen",
        "imageGallery",
        "showBlocks",
        "codeView",
        "print",
      ],
      [
        "-right",
        ":r-Table&Media-default.more_plus",
        "table",
        "link",
        "image",
        "video",
        "audio",
        "math",
      ],
    ],
  ],
  [
    "%893",
    [
      ["undo", "redo"],
      [
        ":p-Formats-default.more_paragraph",
        "font",
        "fontSize",
        "formatBlock",
        "paragraphStyle",
        "blockquote",
      ],
      ["bold", "underline", "italic", "strike"],
      [
        ":t-Fonts-default.more_text",
        "subscript",
        "superscript",
        "fontColor",
        "hiliteColor",
        "textStyle",
      ],
      ["removeFormat"],
      ["outdent", "indent"],
      ["align", "horizontalRule", "list", "lineHeight"],
      // ["-right", "save"],
      [
        "-right",
        ":i-Tiện ích-default.more_vertical",
        // "preview",
        "fullScreen",
        "imageGallery",
        "showBlocks",
        "codeView",
        "print",
      ],
      [
        "-right",
        ":r-Table&Media-default.more_plus",
        "table",
        "link",
        "image",
        "video",
        "audio",
        "math",
      ],
    ],
  ],
  [
    "%855",
    [
      ["undo", "redo"],
      [
        ":p-Formats-default.more_paragraph",
        "font",
        "fontSize",
        "formatBlock",
        "paragraphStyle",
        "blockquote",
      ],
      [
        ":t-Fonts-default.more_text",
        "bold",
        "underline",
        "italic",
        "strike",
        "subscript",
        "superscript",
        "fontColor",
        "hiliteColor",
        "textStyle",
      ],
      ["removeFormat"],
      ["outdent", "indent"],
      ["align", "horizontalRule", "list", "lineHeight"],
      [
        ":r-Table&Media-default.more_plus",
        "table",
        "link",
        "image",
        "video",
        "audio",
        "math",
      ],
      // ["-right", "save"],
      [
        "-right",
        ":i-Tiện ích-default.more_vertical",
        // "preview",
        "fullScreen",
        "imageGallery",
        "showBlocks",
        "codeView",
        "print",
      ],
    ],
  ],
  [
    "%563",
    [
      ["undo", "redo"],
      [
        ":p-Formats-default.more_paragraph",
        "font",
        "fontSize",
        "formatBlock",
        "paragraphStyle",
        "blockquote",
      ],
      [
        ":t-Fonts-default.more_text",
        "bold",
        "underline",
        "italic",
        "strike",
        "subscript",
        "superscript",
        "fontColor",
        "hiliteColor",
        "textStyle",
      ],
      ["removeFormat"],
      ["outdent", "indent"],
      [
        ":e-List&Line-default.more_horizontal",
        "align",
        "horizontalRule",
        "list",
        "lineHeight",
      ],
      [
        ":r-Table&Media-default.more_plus",
        "table",
        "link",
        "image",
        "video",
        "audio",
        "math",
      ],
      // ["-right", "save"],
      [
        "-right",
        ":i-Tiện ích-default.more_vertical",
        // "preview",
        "fullScreen",
        "imageGallery",
        "showBlocks",
        "codeView",
        "print",
      ],
    ],
  ],
  [
    "%458",
    [
      ["undo", "redo"],
      [
        ":p-Formats-default.more_paragraph",
        "font",
        "fontSize",
        "formatBlock",
        "paragraphStyle",
        "blockquote",
      ],
      [
        ":t-Fonts-default.more_text",
        "bold",
        "underline",
        "italic",
        "strike",
        "subscript",
        "superscript",
        "fontColor",
        "hiliteColor",
        "textStyle",
        "removeFormat",
      ],
      [
        ":e-List&Line-default.more_horizontal",
        "outdent",
        "indent",
        "align",
        "horizontalRule",
        "list",
        "lineHeight",
      ],
      [
        ":r-Table&Media-default.more_plus",
        "table",
        "link",
        "image",
        "video",
        "audio",
        "math",
      ],
      // ["-right", "save"],
      [
        "-right",
        ":i-Tiện ích-default.more_vertical",
        // "preview",
        "fullScreen",
        "imageGallery",
        "showBlocks",
        "codeView",
        "print",
      ],
    ],
  ],
];

export const langOptions = {
  toolbar: {
    default: "Mặc định",
    save: "Lưu",
    font: "Phông chữ",
    formats: "Định dạng",
    fontSize: "Cỡ chữ",
    bold: "Đậm",
    underline: "Gạch chân",
    italic: "Nghiêng",
    strike: "Gạch ngang",
    subscript: "Chỉ số dưới",
    superscript: "Chỉ số trên",
    removeFormat: "Xóa định dạng",
    fontColor: "Màu chữ",
    hiliteColor: "Màu nền",
    indent: "Thụt vào",
    outdent: "Thụt ra",
    align: "Căn chỉnh",
    alignLeft: "Căn trái",
    alignRight: "Căn phải",
    alignCenter: "Căn giữa",
    alignJustify: "Căn đều",
    list: "Danh sách",
    orderList: "Danh sách có thứ tự",
    unorderList: "Danh sách không thứ tự",
    horizontalRule: "Đường ngang",
    hr_solid: "Đường ngang liền",
    hr_dotted: "Đường ngang chấm",
    hr_dashed: "Đường ngang gạch",
    table: "Bảng",
    link: "Liên kết",
    math: "Toán học",
    image: "Hình ảnh",
    video: "Video",
    audio: "Âm thanh",
    fullScreen: "Toàn màn hình",
    showBlocks: "Hiển thị khối",
    codeView: "Xem mã",
    undo: "Hoàn tác",
    redo: "Làm lại",
    preview: "Xem trước",
    print: "In",
    tag_p: "Đoạn văn",
    tag_div: "Khối",
    tag_h: "Tiêu đề",
    tag_blockquote: "Trích dẫn",
    tag_pre: "Định dạng trước",
    template: "Mẫu",
    lineHeight: "Chiều cao dòng",
    paragraphStyle: "Kiểu đoạn văn",
    textStyle: "Kiểu chữ",
    imageGallery: "Thư viện ảnh",
    dir_ltr: "Trái sang phải",
    dir_rtl: "Phải sang trái",
    mention: "Đề cập",
  },
  code: "Mã",
  dialogBox: {
    linkBox: {
      title: "Liên kết",
      url: "URL",
      text: "Văn bản",
      newWindowCheck: "Mở trong cửa sổ mới",
      downloadLinkCheck: "Tải xuống liên kết",
      bookmark: "Đánh dấu",
    },
    mathBox: {
      title: "Toán học",
      inputLabel: "Đầu vào",
      fontSizeLabel: "Cỡ chữ",
      previewLabel: "Xem trước",
    },
    imageBox: {
      title: "Hình ảnh",
      file: "Tệp",
      url: "URL",
      altText: "Văn bản thay thế (alt)",
    },
    videoBox: {
      title: "Video",
      file: "Tệp",
      url: "URL",
    },
    audioBox: {
      title: "Âm thanh",
      file: "Tệp",
      url: "URL",
    },
    browser: {
      tags: "Thẻ",
      search: "Tìm kiếm",
    },
    caption: "Chú thích",
    close: "Đóng",
    submitButton: "Gửi",
    revertButton: "Hoàn tác",
    proportion: "Tỷ lệ",
    basic: "Cơ bản",
    left: "Trái",
    right: "Phải",
    center: "Giữa",
    width: "Chiều rộng",
    height: "Chiều cao",
    size: "Kích thước",
    ratio: "Tỷ lệ",
  },
  controller: {
    edit: "Chỉnh sửa",
    unlink: "Bỏ liên kết",
    remove: "Xóa",
    insertRowAbove: "Chèn hàng trên",
    insertRowBelow: "Chèn hàng dưới",
    deleteRow: "Xóa hàng",
    insertColumnBefore: "Chèn cột trước",
    insertColumnAfter: "Chèn cột sau",
    deleteColumn: "Xóa cột",
    fixedColumnWidth: "Chiều rộng cột cố định",
    resize100: "Kích thước 100%",
    resize75: "Kích thước 75%",
    resize50: "Kích thước 50%",
    resize25: "Kích thước 25%",
    autoSize: "Kích thước tự động",
    mirrorHorizontal: "Phản chiếu ngang",
    mirrorVertical: "Phản chiếu dọc",
    rotateLeft: "Xoay trái",
    rotateRight: "Xoay phải",
    maxSize: "Kích thước tối đa",
    minSize: "Kích thước tối thiểu",
    tableHeader: "Tiêu đề bảng",
    mergeCells: "Gộp ô",
    splitCells: "Tách ô",
    HorizontalSplit: "Tách ngang",
    VerticalSplit: "Tách dọc",
  },
  menu: {
    spaced: "Khoảng cách",
    bordered: "Viền",
    neon: "Neon",
    translucent: "Trong suốt",
    shadow: "Bóng",
    code: "Mã",
  },
};

export const colorListOptions = [
  "#FFFFFF",
  "#DDDDDD",
  "#BBBBBB",
  "#999999",
  "#777777",
  "#555555",
  "#333333",
  "#1C1C1C",
  "#111111",

  //Hàng 3: Đỏ
  "#8B0016",
  "#B2001F",
  "#C50023",
  "#DF0029",
  "#E54646",
  "#EE7C6B",
  "#F5A89A",
  "#FCDAD5",
  "#FF0000",

  // ---
  "#976D00",
  "#C18C00",
  "#D59B00",
  "#F1AF00",
  "#F3C246",
  "#F9CC76",
  "#FCE0A6",
  "#FEEBD0",
  "#FFD700",
  //--

  "#367517",
  "#489620",
  "#50A625",
  "#5BBD2B",
  "#83C75D",
  "#AFD788",
  "#C8E2B1",
  "#E6F1D8",
  "#00FF00",

  //--
  "#00676B",
  "#008489",
  "#009298",
  "#00A6AD",
  "#00B2BF",
  "#6EC3C9",
  "#99D1D3",
  "#CAE5E8",
  "#00FFFF",

  //--
  "#2F4F4F",
  "#3C6666",
  "#457272",
  "#4F7D7D",
  "#5C8A8A",
  "#7FA4A4",
  "#9EBDBD",
  "#C0D6D6",
  "#008080",

  //--
  "#103667",
  "#184785",
  "#1B4F93",
  "#205AA7",
  "#426EB4",
  "#7388C1",
  "#94AAD6",
  "#BFCAE6",
  "#0000FF",

  //--
  "#64004B",
  "#780062",
  "#8F006D",
  "#A2007C",
  "#AF4A92",
  "#C57CAC",
  "#D2A6C7",
  "#E8D3E3",
  "#FF00FF",
];

// export const colorListOptions = [
//   // Hàng 1: Trắng đến Xám
//   //"#FFFFFF", "#EEEEEE", "#DDDDDD", "#CCCCCC", "#BBBBBB", "#AAAAAA", "#999999", "#888888", "#777777",
//   // Hàng 2: Xám đậm đến Đen
//   //"#666666", "#555555", "#444444", "#333333", "#222222", "#111111", "#000000", "#000000", "#000000",
//   "#FFFFFF", "#DDDDDD", "#BBBBBB", "#999999", "#777777", "#555555", "#333333", "#111111", "#000000"  ,

//   // // Hàng 3: Đỏ
//   // "#FF0000", "#EE0000", "#DD0000", "#CC0000", "#BB0000", "#AA0000", "#990000", "#880000", "#770000",
//   // // Hàng 4: Đỏ đậm
//   // "#660000", "#550000", "#440000", "#330000", "#220000", "#110000", "#110000", "#110000", "#110000",

//   "#8B0016",
//     "#B2001F",
//   "#C50023",
//   "#DF0029",
//     "#E54646",
//     "#EE7C6B",
//     "#F5A89A",
//     "#FCDAD5", "#FF0000",

//   // // Hàng 5: Vàng
//   // "#FFFF00", "#FFFF33", "#FFFF66", "#FFFF99", "#FFFFCC", "#CCFF00", "#CCFF33", "#CCFF66", "#CCFF99",
//   // // Hàng 6: Vàng nhạt
//   // "#CCFFFF", "#99FF00", "#99FF33", "#99FF66", "#99FF99", "#66FF00", "#66FF33", "#66FF66", "#66FF99",
//   // // Hàng 7: Vàng rất nhạt
//   // "#33FF00", "#33FF33", "#33FF66", "#33FF99", "#00FF00", "#00FF33", "#00FF66", "#00FF99", "#00FFFF",
//   "#FFFF00", "#FFCC33", "#FF9966", "#CCFF00",  "#99FF33", "#66FF66", "#33FF99", "#00FF66", "#00FF00"  ,

//   // Hàng 8: Hồng
//   //"#FF00FF", "#FF33FF", "#FF66FF", "#FF99FF", "#FFCCFF", "#CC00FF", "#CC33FF", "#CC66FF", "#CC99FF",
//   // Hàng 9: Hồng nhạt
//   //"#CCFFFF", "#9900FF", "#9933FF", "#9966FF", "#9999FF", "#6600FF", "#6633FF", "#6666FF", "#6699FF",
//   // Hàng 10: Hồng rất nhạt
//   //"#3300FF", "#3333FF", "#3366FF", "#3399FF", "#0000FF", "#0033FF", "#0066FF", "#0099FF", "#0099FF",

//   // // Hàng 11: Cam
//   // "#FFCC00", "#FFCC33", "#FFCC66", "#FFCC99", "#FFCCCC", "#CC9900", "#CC9933", "#CC9966", "#CC9999",
//   // // Hàng 12: Cam nhạt
//   // "#99CC00", "#99CC33", "#99CC66", "#99CC99", "#99CCCC", "#66CC00", "#66CC33", "#66CC66", "#66CC99",
//   // // Hàng 13: Cam rất nhạt
//   // "#33CC00", "#33CC33", "#33CC66", "#33CC99", "#00CC00", "#00CC33", "#00CC66", "#00CC99", "#00CCCC",
//   "#FFCC00", "#FFCC66", "#FFCC99",
//   "#CC9900", "#CC9966", "#99CC00",
//   "#66CC33", "#33CC66", "#00CC00",

//   // // Hàng 14: Xanh lá cây
//   // "#00FF00", "#00EE00", "#00DD00", "#00CC00", "#00BB00", "#00AA00", "#009900", "#008800", "#007700",
//   // // Hàng 15: Xanh lá cây đậm
//   // "#006600", "#005500", "#004400", "#003300", "#002200", "#001100", "#001100", "#001100", "#001100",
//    "#00FF00", "#00DD00", "#00BB00", "#009900",
//     "#007700", "#005500", "#003300", "#002200", "#001100"  ,

//   // // Hàng 16: Xanh lam
//   // "#0000FF", "#0000EE", "#0000DD", "#0000CC", "#0000BB", "#0000AA", "#000099", "#000088", "#000077",
//   // // Hàng 17: Xanh lam đậm
//   //  "#000066", "#000055", "#000044", "#000033", "#000022", "#000011", "#000011", "#000011", "#000011",
//    "#0000FF", "#0000DD", "#0000BB", "#000099",
//     "#000077", "#000055", "#000033", "#000022", "#000011"  ,

//   // Hàng 18: Xanh dương
//   "#00FFFF", "#00EEEE", "#00DDDD", "#00CCCC", "#00BBBB", "#00AAAA", "#009999", "#008888", "#007777",

//   ];
